### PR TITLE
Fixes fatal flaw in architecture design

### PR DESCRIPTION
**Pull request by downgear**
The bird could have possibly died. Why are you so careless???

https://github.com/khoakomlem/simple-flappybird/assets/134379113/4d608f24-dab0-4e9d-9c1c-da0b6dad18b9

### CODE REVIEW

**Comment by beanbocchi** [comment]
Dang..

**Comment by downgear** [comment]
nah  I'd close

**Comment by beanbocchi** [comment]
Nuh uh

**Comment by beanbocchi** [comment]
We dont do that here

**Comment by downgear** [comment]
**THIS CONVERSATION IS OVER.**

**Comment by beanbocchi** [comment]
I do not agreed

**Comment by beanbocchi** [comment]
New Bitmap Image

**Comment by beanbocchi** [comment]
please reopen ASAP

**Comment by downgear** [comment]
please

**Comment by downgear** [comment]
unmaintained btư

**Pull request closed without merging**
